/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor 

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   ODBootloader.h; ODBootloader.c
        Project File: Bootloader.eds
        File Version: 0

        Created:      12. 12. 2024 16:31:00
        Created By:   Unknown
        Modified:     12. 12. 2024 19:51:00
        Modified By:  Unknown

    Device Info:
        Vendor Name:  Unknown
        Vendor ID:    0x00000000
        Product Name: Unknown
        Product ID:   0x00000000

        Description:  None
*******************************************************************************/

#ifndef ODBootloader_H
#define ODBootloader_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define ODBootloader_CNT_HB_CONS 1
#define ODBootloader_CNT_HB_PROD 1
#define ODBootloader_CNT_NMT 1
#define ODBootloader_CNT_EM 1
#define ODBootloader_CNT_EM_PROD 1
#define ODBootloader_CNT_SDO_SRV 1
#define ODBootloader_CNT_SDO_CLI 0
#define ODBootloader_CNT_TIME 1
#define ODBootloader_CNT_SYNC 1
#define ODBootloader_CNT_RPDO 2
#define ODBootloader_CNT_TPDO 7
#define ODBootloader_CNT_GFC 0
#define ODBootloader_CNT_SRDO 0


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define ODBootloader_CNT_ARR_1003 4
#define ODBootloader_CNT_ARR_1010 4
#define ODBootloader_CNT_ARR_1011 4
#define ODBootloader_CNT_ARR_1016 4
#define ODBootloader_CNT_ARR_1020 2
#define ODBootloader_CNT_ARR_6001 2
#define ODBootloader_CNT_ARR_6002 2
#define ODBootloader_CNT_ARR_6003 4
#define ODBootloader_CNT_ARR_6004 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1002_manufacturerStatusRegister;
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[ODBootloader_CNT_ARR_1003];
    uint32_t x1005_SYNC_COB_ID;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    char x1008_manufacturerDeviceName[9];
    char x1009_manufacturerHardwareVersion[9];
    char x100A_manufacturerSoftwareVersion[9];
    uint8_t x1010_storeParameters_sub0;
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1012_timeStampCOB_ID;
    uint32_t x1013_highResolutionTimeStamp;
    uint32_t x1014_emergencyCOB_ID;
    uint16_t x1015_emergencyInhibitTime;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[ODBootloader_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1020_verifyConfiguration_sub0;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDO_Server;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDClientToServerRX;
        uint32_t COB_IDServerToClientTX;
        uint8_t IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1400_receivePDO_Communication_1;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1401_receivePDO_Communication_2;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
    } x1600_receivePDO_Mapping_1;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
    } x1601_receivePDO_Mapping_2;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1800_transmitPDO_Communication_1;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1801_transmitPDO_Communication_2;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1802_transmitPDO_Communication_3;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1804_transmitPDO_Communication_5;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1805_transmitPDO_Communication_6;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1806_transmitPDO_Communication_7;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1807_transmitPDO_Communication_8;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
    } x1A00_transmitPDO_Mapping_1;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
    } x1A01_transmitPDO_Mapping_2;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
    } x1A02_transmitPDO_Mapping_3;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
    } x1A04_transmitPDO_Mapping_5;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
    } x1A05_transmitPDO_Mapping_6;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
    } x1A06_transmitPDO_Mapping_7;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
    } x1A07_transmitPDO_Mapping_8;
    uint32_t x6000_firmware_crc32;
    uint32_t x6001_firmware_size;
} ODBootloader_RAM_t;

#ifndef ODBootloader_ATTR_RAM
#define ODBootloader_ATTR_RAM
#endif
extern ODBootloader_ATTR_RAM ODBootloader_RAM_t ODBootloader_RAM;

#ifndef ODBootloader_ATTR_OD
#define ODBootloader_ATTR_OD
#endif
extern ODBootloader_ATTR_OD OD_t *ODBootloader;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define ODBootloader_ENTRY_H1000 &ODBootloader->list[0]
#define ODBootloader_ENTRY_H1001 &ODBootloader->list[1]
#define ODBootloader_ENTRY_H1002 &ODBootloader->list[2]
#define ODBootloader_ENTRY_H1003 &ODBootloader->list[3]
#define ODBootloader_ENTRY_H1005 &ODBootloader->list[4]
#define ODBootloader_ENTRY_H1006 &ODBootloader->list[5]
#define ODBootloader_ENTRY_H1007 &ODBootloader->list[6]
#define ODBootloader_ENTRY_H1008 &ODBootloader->list[7]
#define ODBootloader_ENTRY_H1009 &ODBootloader->list[8]
#define ODBootloader_ENTRY_H100A &ODBootloader->list[9]
#define ODBootloader_ENTRY_H1010 &ODBootloader->list[10]
#define ODBootloader_ENTRY_H1011 &ODBootloader->list[11]
#define ODBootloader_ENTRY_H1012 &ODBootloader->list[12]
#define ODBootloader_ENTRY_H1013 &ODBootloader->list[13]
#define ODBootloader_ENTRY_H1014 &ODBootloader->list[14]
#define ODBootloader_ENTRY_H1015 &ODBootloader->list[15]
#define ODBootloader_ENTRY_H1016 &ODBootloader->list[16]
#define ODBootloader_ENTRY_H1017 &ODBootloader->list[17]
#define ODBootloader_ENTRY_H1018 &ODBootloader->list[18]
#define ODBootloader_ENTRY_H1019 &ODBootloader->list[19]
#define ODBootloader_ENTRY_H1020 &ODBootloader->list[20]
#define ODBootloader_ENTRY_H1200 &ODBootloader->list[21]
#define ODBootloader_ENTRY_H1280 &ODBootloader->list[22]
#define ODBootloader_ENTRY_H1400 &ODBootloader->list[23]
#define ODBootloader_ENTRY_H1401 &ODBootloader->list[24]
#define ODBootloader_ENTRY_H1600 &ODBootloader->list[25]
#define ODBootloader_ENTRY_H1601 &ODBootloader->list[26]
#define ODBootloader_ENTRY_H1800 &ODBootloader->list[27]
#define ODBootloader_ENTRY_H1801 &ODBootloader->list[28]
#define ODBootloader_ENTRY_H1802 &ODBootloader->list[29]
#define ODBootloader_ENTRY_H1804 &ODBootloader->list[30]
#define ODBootloader_ENTRY_H1805 &ODBootloader->list[31]
#define ODBootloader_ENTRY_H1806 &ODBootloader->list[32]
#define ODBootloader_ENTRY_H1807 &ODBootloader->list[33]
#define ODBootloader_ENTRY_H1A00 &ODBootloader->list[34]
#define ODBootloader_ENTRY_H1A01 &ODBootloader->list[35]
#define ODBootloader_ENTRY_H1A02 &ODBootloader->list[36]
#define ODBootloader_ENTRY_H1A04 &ODBootloader->list[37]
#define ODBootloader_ENTRY_H1A05 &ODBootloader->list[38]
#define ODBootloader_ENTRY_H1A06 &ODBootloader->list[39]
#define ODBootloader_ENTRY_H1A07 &ODBootloader->list[40]
#define ODBootloader_ENTRY_H6000 &ODBootloader->list[41]
#define ODBootloader_ENTRY_H6001 &ODBootloader->list[42]
#define ODBootloader_ENTRY_H6002 &ODBootloader->list[43]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define ODBootloader_ENTRY_H1000_deviceType &ODBootloader->list[0]
#define ODBootloader_ENTRY_H1001_errorRegister &ODBootloader->list[1]
#define ODBootloader_ENTRY_H1002_manufacturerStatusRegister &ODBootloader->list[2]
#define ODBootloader_ENTRY_H1003_pre_definedErrorField &ODBootloader->list[3]
#define ODBootloader_ENTRY_H1005_SYNC_COB_ID &ODBootloader->list[4]
#define ODBootloader_ENTRY_H1006_communicationCyclePeriod &ODBootloader->list[5]
#define ODBootloader_ENTRY_H1007_synchronousWindowLength &ODBootloader->list[6]
#define ODBootloader_ENTRY_H1008_manufacturerDeviceName &ODBootloader->list[7]
#define ODBootloader_ENTRY_H1009_manufacturerHardwareVersion &ODBootloader->list[8]
#define ODBootloader_ENTRY_H100A_manufacturerSoftwareVersion &ODBootloader->list[9]
#define ODBootloader_ENTRY_H1010_storeParameters &ODBootloader->list[10]
#define ODBootloader_ENTRY_H1011_restoreDefaultParameters &ODBootloader->list[11]
#define ODBootloader_ENTRY_H1012_timeStampCOB_ID &ODBootloader->list[12]
#define ODBootloader_ENTRY_H1013_highResolutionTimeStamp &ODBootloader->list[13]
#define ODBootloader_ENTRY_H1014_emergencyCOB_ID &ODBootloader->list[14]
#define ODBootloader_ENTRY_H1015_emergencyInhibitTime &ODBootloader->list[15]
#define ODBootloader_ENTRY_H1016_consumerHeartbeatTime &ODBootloader->list[16]
#define ODBootloader_ENTRY_H1017_producerHeartbeatTime &ODBootloader->list[17]
#define ODBootloader_ENTRY_H1018_identity &ODBootloader->list[18]
#define ODBootloader_ENTRY_H1019_synchronousCounterOverflowValue &ODBootloader->list[19]
#define ODBootloader_ENTRY_H1020_verifyConfiguration &ODBootloader->list[20]
#define ODBootloader_ENTRY_H1200_SDO_Server &ODBootloader->list[21]
#define ODBootloader_ENTRY_H1280_SDOClientParameter &ODBootloader->list[22]
#define ODBootloader_ENTRY_H1400_receivePDO_Communication_1 &ODBootloader->list[23]
#define ODBootloader_ENTRY_H1401_receivePDO_Communication_2 &ODBootloader->list[24]
#define ODBootloader_ENTRY_H1600_receivePDO_Mapping_1 &ODBootloader->list[25]
#define ODBootloader_ENTRY_H1601_receivePDO_Mapping_2 &ODBootloader->list[26]
#define ODBootloader_ENTRY_H1800_transmitPDO_Communication_1 &ODBootloader->list[27]
#define ODBootloader_ENTRY_H1801_transmitPDO_Communication_2 &ODBootloader->list[28]
#define ODBootloader_ENTRY_H1802_transmitPDO_Communication_3 &ODBootloader->list[29]
#define ODBootloader_ENTRY_H1804_transmitPDO_Communication_5 &ODBootloader->list[30]
#define ODBootloader_ENTRY_H1805_transmitPDO_Communication_6 &ODBootloader->list[31]
#define ODBootloader_ENTRY_H1806_transmitPDO_Communication_7 &ODBootloader->list[32]
#define ODBootloader_ENTRY_H1807_transmitPDO_Communication_8 &ODBootloader->list[33]
#define ODBootloader_ENTRY_H1A00_transmitPDO_Mapping_1 &ODBootloader->list[34]
#define ODBootloader_ENTRY_H1A01_transmitPDO_Mapping_2 &ODBootloader->list[35]
#define ODBootloader_ENTRY_H1A02_transmitPDO_Mapping_3 &ODBootloader->list[36]
#define ODBootloader_ENTRY_H1A04_transmitPDO_Mapping_5 &ODBootloader->list[37]
#define ODBootloader_ENTRY_H1A05_transmitPDO_Mapping_6 &ODBootloader->list[38]
#define ODBootloader_ENTRY_H1A06_transmitPDO_Mapping_7 &ODBootloader->list[39]
#define ODBootloader_ENTRY_H1A07_transmitPDO_Mapping_8 &ODBootloader->list[40]
#define ODBootloader_ENTRY_H6000_firmware_crc &ODBootloader->list[41]
#define ODBootloader_ENTRY_H6001_firmware_size &ODBootloader->list[42]
#define ODBootloader_ENTRY_H6003_firmware_binary &ODBootloader->list[43]



/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define ODBootloader_INIT_CONFIG(config) {\
    (config).CNT_NMT = ODBootloader_CNT_NMT;\
    (config).ENTRY_H1017 = ODBootloader_ENTRY_H1017;\
    (config).CNT_HB_CONS = ODBootloader_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = ODBootloader_CNT_ARR_1016;\
    (config).ENTRY_H1016 = ODBootloader_ENTRY_H1016;\
    (config).CNT_EM = ODBootloader_CNT_EM;\
    (config).ENTRY_H1001 = ODBootloader_ENTRY_H1001;\
    (config).ENTRY_H1014 = ODBootloader_ENTRY_H1014;\
    (config).ENTRY_H1015 = ODBootloader_ENTRY_H1015;\
    (config).CNT_ARR_1003 = ODBootloader_CNT_ARR_1003;\
    (config).ENTRY_H1003 = ODBootloader_ENTRY_H1003;\
    (config).CNT_SDO_SRV = ODBootloader_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = ODBootloader_ENTRY_H1200;\
    (config).CNT_SDO_CLI = ODBootloader_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = ODBootloader_ENTRY_H1280;\
    (config).CNT_TIME = ODBootloader_CNT_TIME;\
    (config).ENTRY_H1012 = ODBootloader_ENTRY_H1012;\
    (config).CNT_SYNC = ODBootloader_CNT_SYNC;\
    (config).ENTRY_H1005 = ODBootloader_ENTRY_H1005;\
    (config).ENTRY_H1006 = ODBootloader_ENTRY_H1006;\
    (config).ENTRY_H1007 = ODBootloader_ENTRY_H1007;\
    (config).ENTRY_H1019 = ODBootloader_ENTRY_H1019;\
    (config).CNT_RPDO = ODBootloader_CNT_RPDO;\
    (config).ENTRY_H1400 = ODBootloader_ENTRY_H1400;\
    (config).ENTRY_H1600 = ODBootloader_ENTRY_H1600;\
    (config).CNT_TPDO = ODBootloader_CNT_TPDO;\
    (config).ENTRY_H1800 = ODBootloader_ENTRY_H1800;\
    (config).ENTRY_H1A00 = ODBootloader_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = ODBootloader_CNT_GFC;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = ODBootloader_CNT_SRDO;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* ODBootloader_H */
