/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor 

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION

#include "301/CO_ODinterface.h"
#include "ODBootloader.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
ODBootloader_ATTR_RAM ODBootloader_RAM_t ODBootloader_RAM = {
        .x1000_deviceType = 0x00000191,
        .x1001_errorRegister = 0x00,
        .x1002_manufacturerStatusRegister = 0x00000000,
        .x1003_pre_definedErrorField_sub0 = 0x00,
        .x1003_pre_definedErrorField = {0x00000000, 0x00000000, 0x00000000, 0x00000000},
        .x1005_SYNC_COB_ID = 0x00000080,
        .x1006_communicationCyclePeriod = 0x00000000,
        .x1007_synchronousWindowLength = 0x00000000,
        .x1008_manufacturerDeviceName = {'1', '2', '3', '4', '5', '6', '7', '8', 0},
        .x1009_manufacturerHardwareVersion = {'1', '2', '3', '4', '5', '6', '7', '8', 0},
        .x100A_manufacturerSoftwareVersion = {'1', '2', '3', '4', '5', '6', '7', '8', 0},
        .x1010_storeParameters_sub0 = 0x04,
        .x1011_restoreDefaultParameters_sub0 = 0x04,
        .x1012_timeStampCOB_ID = 0x00000100,
        .x1013_highResolutionTimeStamp = 0x00000000,
        .x1014_emergencyCOB_ID = 0x00000080,
        .x1015_emergencyInhibitTime = 0x0000,
        .x1016_consumerHeartbeatTime_sub0 = 0x04,
        .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000},
        .x1017_producerHeartbeatTime = 0x00C8,
        .x1018_identity = {
                .numberOfEntries = 0x04,
                .vendorID = 0x00000000,
                .productCode = 0x00000000,
                .revisionNumber = 0x00000000,
                .serialNumber = 0x00000000
        },
        .x1020_verifyConfiguration_sub0 = 0x02,
        .x1200_SDO_Server = {
                .highestSubindex = 0x02,
                .COB_IDClientToServerRx = 0x00000600,
                .COB_IDServerToClientTx = 0x00000580
        },
        .x1280_SDOClientParameter = {
                .highestSubindex = 0x03,
                .COB_IDClientToServerRX = 0x80000000,
                .COB_IDServerToClientTX = 0x80000000,
                .IDOfTheSDOServer = 0x01
        },
        .x1400_receivePDO_Communication_1 = {
                .highestSubindex = 0x02,
                .COB_IDUsedByPDO = 0x40000381,
                .transmissionType = 0xFF
        },
        .x1401_receivePDO_Communication_2 = {
                .highestSubindex = 0x02,
                .COB_IDUsedByPDO = 0x40000481,
                .transmissionType = 0xFF
        },
        .x1600_receivePDO_Mapping_1 = {
                .highestSubindex = 0x01,
                .mapping_1 = 0x60110008
        },
        .x1601_receivePDO_Mapping_2 = {
                .highestSubindex = 0x01,
                .mapping_1 = 0x60100008
        },
        .x1800_transmitPDO_Communication_1 = {
                .highestSubindex = 0x06,
                .COB_IDUsedByPDO = 0x40000289,
                .transmissionType = 0x00,
                .inhibitTime = 0x0000,
                .eventTimer = 0x000A,
                .syncStartValue = 0x00
        },
        .x1801_transmitPDO_Communication_2 = {
                .highestSubindex = 0x06,
                .COB_IDUsedByPDO = 0x4000028A,
                .transmissionType = 0x00,
                .inhibitTime = 0x0000,
                .eventTimer = 0x000A,
                .syncStartValue = 0x00
        },
        .x1802_transmitPDO_Communication_3 = {
                .highestSubindex = 0x06,
                .COB_IDUsedByPDO = 0x40000189,
                .transmissionType = 0x00,
                .inhibitTime = 0x0000,
                .eventTimer = 0x0064,
                .syncStartValue = 0x00
        },
        .x1804_transmitPDO_Communication_5 = {
                .highestSubindex = 0x06,
                .COB_IDUsedByPDO = 0x40000489,
                .transmissionType = 0xFF,
                .inhibitTime = 0x0000,
                .eventTimer = 0x03E8,
                .syncStartValue = 0x00
        },
        .x1805_transmitPDO_Communication_6 = {
                .highestSubindex = 0x06,
                .COB_IDUsedByPDO = 0x4000048A,
                .transmissionType = 0xFF,
                .inhibitTime = 0x0000,
                .eventTimer = 0x03E8,
                .syncStartValue = 0x00
        },
        .x1806_transmitPDO_Communication_7 = {
                .highestSubindex = 0x06,
                .COB_IDUsedByPDO = 0x4000048B,
                .transmissionType = 0xFF,
                .inhibitTime = 0x0000,
                .eventTimer = 0x03E8,
                .syncStartValue = 0x00
        },
        .x1807_transmitPDO_Communication_8 = {
                .highestSubindex = 0x06,
                .COB_IDUsedByPDO = 0x4000048C,
                .transmissionType = 0xFF,
                .inhibitTime = 0x0000,
                .eventTimer = 0x03E8,
                .syncStartValue = 0x00
        },
        .x1A00_transmitPDO_Mapping_1 = {
                .highestSubindex = 0x01,
                .mapping_1 = 0x60000020
        },
        .x1A01_transmitPDO_Mapping_2 = {
                .highestSubindex = 0x02,
                .mapping_1 = 0x60010120,
                .mapping_2 = 0x60010220
        },
        .x1A02_transmitPDO_Mapping_3 = {
                .highestSubindex = 0x01,
                .mapping_1 = 0x60050008
        },
        .x1A04_transmitPDO_Mapping_5 = {
                .highestSubindex = 0x02,
                .mapping_1 = 0x20000020,
                .mapping_2 = 0x20010020
        },
        .x1A05_transmitPDO_Mapping_6 = {
                .highestSubindex = 0x02,
                .mapping_1 = 0x20020020,
                .mapping_2 = 0x20030020
        },
        .x1A06_transmitPDO_Mapping_7 = {
                .highestSubindex = 0x02,
                .mapping_1 = 0x20040020,
                .mapping_2 = 0x20050020
        },
        .x1A07_transmitPDO_Mapping_8 = {
                .highestSubindex = 0x02,
                .mapping_1 = 0x20060020,
                .mapping_2 = 0x20070020
        },
        .x6000_firmware_crc32 = 0x00000000,
        .x6001_firmware_size = 0x00000000
};


/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1002_manufacturerStatusRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_SYNC_COB_ID;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_timeStampCOB_ID;
    OD_obj_var_t o_1013_highResolutionTimeStamp;
    OD_obj_var_t o_1014_emergencyCOB_ID;
    OD_obj_var_t o_1015_emergencyInhibitTime;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_array_t o_1020_verifyConfiguration;
    OD_obj_record_t o_1200_SDO_Server[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_receivePDO_Communication_1[3];
    OD_obj_record_t o_1401_receivePDO_Communication_2[3];
    OD_obj_record_t o_1600_receivePDO_Mapping_1[2];
    OD_obj_record_t o_1601_receivePDO_Mapping_2[2];
    OD_obj_record_t o_1800_transmitPDO_Communication_1[6];
    OD_obj_record_t o_1801_transmitPDO_Communication_2[6];
    OD_obj_record_t o_1802_transmitPDO_Communication_3[6];
    OD_obj_record_t o_1804_transmitPDO_Communication_5[6];
    OD_obj_record_t o_1805_transmitPDO_Communication_6[6];
    OD_obj_record_t o_1806_transmitPDO_Communication_7[6];
    OD_obj_record_t o_1807_transmitPDO_Communication_8[6];
    OD_obj_record_t o_1A00_transmitPDO_Mapping_1[2];
    OD_obj_record_t o_1A01_transmitPDO_Mapping_2[3];
    OD_obj_record_t o_1A02_transmitPDO_Mapping_3[2];
    OD_obj_record_t o_1A04_transmitPDO_Mapping_5[3];
    OD_obj_record_t o_1A05_transmitPDO_Mapping_6[3];
    OD_obj_record_t o_1A06_transmitPDO_Mapping_7[3];
    OD_obj_record_t o_1A07_transmitPDO_Mapping_8[3];
    OD_obj_var_t o_6000_firmware_crc32;
    OD_obj_var_t o_6001_firmware_size;
    OD_obj_var_t o_6003_firmware_binary;
} ODBootloaderObjs_t;

static CO_PROGMEM ODBootloaderObjs_t ODBootloaderObjs = {
        .o_1000_deviceType = {
                .dataOrig = &ODBootloader_RAM.x1000_deviceType,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
        },
        .o_1001_errorRegister = {
                .dataOrig = &ODBootloader_RAM.x1001_errorRegister,
                .attribute = ODA_SDO_R | ODA_TRPDO,
                .dataLength = 1
        },
        .o_1002_manufacturerStatusRegister = {
                .dataOrig = &ODBootloader_RAM.x1002_manufacturerStatusRegister,
                .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                .dataLength = 4
        },
        .o_1003_pre_definedErrorField = {
                .dataOrig0 = &ODBootloader_RAM.x1003_pre_definedErrorField_sub0,
                .dataOrig = &ODBootloader_RAM.x1003_pre_definedErrorField[0],
                .attribute0 = ODA_SDO_RW,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1005_SYNC_COB_ID = {
                .dataOrig = &ODBootloader_RAM.x1005_SYNC_COB_ID,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
        },
        .o_1006_communicationCyclePeriod = {
                .dataOrig = &ODBootloader_RAM.x1006_communicationCyclePeriod,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
        },
        .o_1007_synchronousWindowLength = {
                .dataOrig = &ODBootloader_RAM.x1007_synchronousWindowLength,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
        },
        .o_1008_manufacturerDeviceName = {
                .dataOrig = &ODBootloader_RAM.x1008_manufacturerDeviceName[0],
                .attribute = ODA_SDO_R | ODA_STR,
                .dataLength = 8
        },
        .o_1009_manufacturerHardwareVersion = {
                .dataOrig = &ODBootloader_RAM.x1009_manufacturerHardwareVersion[0],
                .attribute = ODA_SDO_R | ODA_STR,
                .dataLength = 8
        },
        .o_100A_manufacturerSoftwareVersion = {
                .dataOrig = &ODBootloader_RAM.x100A_manufacturerSoftwareVersion[0],
                .attribute = ODA_SDO_R | ODA_STR,
                .dataLength = 8
        },
        .o_1010_storeParameters = {
                .dataOrig0 = &ODBootloader_RAM.x1010_storeParameters_sub0,
                .dataOrig = NULL,
                .attribute0 = ODA_SDO_R,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1011_restoreDefaultParameters = {
                .dataOrig0 = &ODBootloader_RAM.x1011_restoreDefaultParameters_sub0,
                .dataOrig = NULL,
                .attribute0 = ODA_SDO_R,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1012_timeStampCOB_ID = {
                .dataOrig = &ODBootloader_RAM.x1012_timeStampCOB_ID,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
        },
        .o_1013_highResolutionTimeStamp = {
                .dataOrig = &ODBootloader_RAM.x1013_highResolutionTimeStamp,
                .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                .dataLength = 4
        },
        .o_1014_emergencyCOB_ID = {
                .dataOrig = &ODBootloader_RAM.x1014_emergencyCOB_ID,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
        },
        .o_1015_emergencyInhibitTime = {
                .dataOrig = &ODBootloader_RAM.x1015_emergencyInhibitTime,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
        },
        .o_1016_consumerHeartbeatTime = {
                .dataOrig0 = &ODBootloader_RAM.x1016_consumerHeartbeatTime_sub0,
                .dataOrig = &ODBootloader_RAM.x1016_consumerHeartbeatTime[0],
                .attribute0 = ODA_SDO_R,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1017_producerHeartbeatTime = {
                .dataOrig = &ODBootloader_RAM.x1017_producerHeartbeatTime,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
        },
        .o_1018_identity = {
                {
                        .dataOrig = &ODBootloader_RAM.x1018_identity.numberOfEntries,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1018_identity.vendorID,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1018_identity.productCode,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1018_identity.revisionNumber,
                        .subIndex = 3,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1018_identity.serialNumber,
                        .subIndex = 4,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1019_synchronousCounterOverflowValue = {
                .dataOrig = NULL,
                .attribute = ODA_SDO_R,
                .dataLength = 1
        },
        .o_1020_verifyConfiguration = {
                .dataOrig0 = &ODBootloader_RAM.x1020_verifyConfiguration_sub0,
                .dataOrig = NULL,
                .attribute0 = ODA_SDO_R,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1200_SDO_Server = {
                {
                        .dataOrig = &ODBootloader_RAM.x1200_SDO_Server.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1200_SDO_Server.COB_IDClientToServerRx,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1200_SDO_Server.COB_IDServerToClientTx,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1280_SDOClientParameter = {
                {
                        .dataOrig = &ODBootloader_RAM.x1280_SDOClientParameter.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1280_SDOClientParameter.COB_IDClientToServerRX,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1280_SDOClientParameter.COB_IDServerToClientTX,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1280_SDOClientParameter.IDOfTheSDOServer,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1400_receivePDO_Communication_1 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1400_receivePDO_Communication_1.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1400_receivePDO_Communication_1.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1400_receivePDO_Communication_1.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1401_receivePDO_Communication_2 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1401_receivePDO_Communication_2.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1401_receivePDO_Communication_2.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1401_receivePDO_Communication_2.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1600_receivePDO_Mapping_1 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1600_receivePDO_Mapping_1.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1600_receivePDO_Mapping_1.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1601_receivePDO_Mapping_2 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1601_receivePDO_Mapping_2.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1601_receivePDO_Mapping_2.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1800_transmitPDO_Communication_1 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1800_transmitPDO_Communication_1.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1800_transmitPDO_Communication_1.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1800_transmitPDO_Communication_1.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1800_transmitPDO_Communication_1.inhibitTime,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1800_transmitPDO_Communication_1.eventTimer,
                        .subIndex = 5,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1800_transmitPDO_Communication_1.syncStartValue,
                        .subIndex = 6,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1801_transmitPDO_Communication_2 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1801_transmitPDO_Communication_2.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1801_transmitPDO_Communication_2.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1801_transmitPDO_Communication_2.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1801_transmitPDO_Communication_2.inhibitTime,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1801_transmitPDO_Communication_2.eventTimer,
                        .subIndex = 5,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1801_transmitPDO_Communication_2.syncStartValue,
                        .subIndex = 6,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1802_transmitPDO_Communication_3 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1802_transmitPDO_Communication_3.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1802_transmitPDO_Communication_3.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1802_transmitPDO_Communication_3.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1802_transmitPDO_Communication_3.inhibitTime,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1802_transmitPDO_Communication_3.eventTimer,
                        .subIndex = 5,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1802_transmitPDO_Communication_3.syncStartValue,
                        .subIndex = 6,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1804_transmitPDO_Communication_5 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1804_transmitPDO_Communication_5.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1804_transmitPDO_Communication_5.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1804_transmitPDO_Communication_5.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1804_transmitPDO_Communication_5.inhibitTime,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1804_transmitPDO_Communication_5.eventTimer,
                        .subIndex = 5,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1804_transmitPDO_Communication_5.syncStartValue,
                        .subIndex = 6,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1805_transmitPDO_Communication_6 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1805_transmitPDO_Communication_6.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1805_transmitPDO_Communication_6.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1805_transmitPDO_Communication_6.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1805_transmitPDO_Communication_6.inhibitTime,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1805_transmitPDO_Communication_6.eventTimer,
                        .subIndex = 5,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1805_transmitPDO_Communication_6.syncStartValue,
                        .subIndex = 6,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1806_transmitPDO_Communication_7 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1806_transmitPDO_Communication_7.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1806_transmitPDO_Communication_7.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1806_transmitPDO_Communication_7.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1806_transmitPDO_Communication_7.inhibitTime,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1806_transmitPDO_Communication_7.eventTimer,
                        .subIndex = 5,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1806_transmitPDO_Communication_7.syncStartValue,
                        .subIndex = 6,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1807_transmitPDO_Communication_8 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1807_transmitPDO_Communication_8.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1807_transmitPDO_Communication_8.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1807_transmitPDO_Communication_8.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1807_transmitPDO_Communication_8.inhibitTime,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1807_transmitPDO_Communication_8.eventTimer,
                        .subIndex = 5,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1807_transmitPDO_Communication_8.syncStartValue,
                        .subIndex = 6,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1A00_transmitPDO_Mapping_1 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1A00_transmitPDO_Mapping_1.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A00_transmitPDO_Mapping_1.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1A01_transmitPDO_Mapping_2 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1A01_transmitPDO_Mapping_2.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A01_transmitPDO_Mapping_2.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A01_transmitPDO_Mapping_2.mapping_2,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1A02_transmitPDO_Mapping_3 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1A02_transmitPDO_Mapping_3.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A02_transmitPDO_Mapping_3.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1A04_transmitPDO_Mapping_5 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1A04_transmitPDO_Mapping_5.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A04_transmitPDO_Mapping_5.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A04_transmitPDO_Mapping_5.mapping_2,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1A05_transmitPDO_Mapping_6 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1A05_transmitPDO_Mapping_6.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A05_transmitPDO_Mapping_6.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A05_transmitPDO_Mapping_6.mapping_2,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1A06_transmitPDO_Mapping_7 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1A06_transmitPDO_Mapping_7.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A06_transmitPDO_Mapping_7.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A06_transmitPDO_Mapping_7.mapping_2,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1A07_transmitPDO_Mapping_8 = {
                {
                        .dataOrig = &ODBootloader_RAM.x1A07_transmitPDO_Mapping_8.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A07_transmitPDO_Mapping_8.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODBootloader_RAM.x1A07_transmitPDO_Mapping_8.mapping_2,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_6000_firmware_crc32 = {
                .dataOrig = &ODBootloader_RAM.x6000_firmware_crc32,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
        },
        .o_6001_firmware_size = {
                .dataOrig = &ODBootloader_RAM.x6001_firmware_size,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
        },
        .o_6003_firmware_binary = {
                .dataOrig = NULL,
                .attribute = ODA_SDO_RW,
                .dataLength = 0
        }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static ODBootloader_ATTR_OD OD_entry_t ODBootloaderList[] = {
        {0x1000, 0x01, ODT_VAR, &ODBootloaderObjs.o_1000_deviceType,                      NULL},
        {0x1001, 0x01, ODT_VAR, &ODBootloaderObjs.o_1001_errorRegister,                   NULL},
        {0x1002, 0x01, ODT_VAR, &ODBootloaderObjs.o_1002_manufacturerStatusRegister,      NULL},
        {0x1003, 0x05, ODT_ARR, &ODBootloaderObjs.o_1003_pre_definedErrorField,           NULL},
        {0x1005, 0x01, ODT_VAR, &ODBootloaderObjs.o_1005_SYNC_COB_ID,                     NULL},
        {0x1006, 0x01, ODT_VAR, &ODBootloaderObjs.o_1006_communicationCyclePeriod,        NULL},
        {0x1007, 0x01, ODT_VAR, &ODBootloaderObjs.o_1007_synchronousWindowLength,         NULL},
        {0x1008, 0x01, ODT_VAR, &ODBootloaderObjs.o_1008_manufacturerDeviceName,          NULL},
        {0x1009, 0x01, ODT_VAR, &ODBootloaderObjs.o_1009_manufacturerHardwareVersion,     NULL},
        {0x100A, 0x01, ODT_VAR, &ODBootloaderObjs.o_100A_manufacturerSoftwareVersion,     NULL},
        {0x1010, 0x05, ODT_ARR, &ODBootloaderObjs.o_1010_storeParameters,                 NULL},
        {0x1011, 0x05, ODT_ARR, &ODBootloaderObjs.o_1011_restoreDefaultParameters,        NULL},
        {0x1012, 0x01, ODT_VAR, &ODBootloaderObjs.o_1012_timeStampCOB_ID,                 NULL},
        {0x1013, 0x01, ODT_VAR, &ODBootloaderObjs.o_1013_highResolutionTimeStamp,         NULL},
        {0x1014, 0x01, ODT_VAR, &ODBootloaderObjs.o_1014_emergencyCOB_ID,                 NULL},
        {0x1015, 0x01, ODT_VAR, &ODBootloaderObjs.o_1015_emergencyInhibitTime,            NULL},
        {0x1016, 0x05, ODT_ARR, &ODBootloaderObjs.o_1016_consumerHeartbeatTime,           NULL},
        {0x1017, 0x01, ODT_VAR, &ODBootloaderObjs.o_1017_producerHeartbeatTime,           NULL},
        {0x1018, 0x05, ODT_REC, &ODBootloaderObjs.o_1018_identity,                        NULL},
        {0x1019, 0x01, ODT_VAR, &ODBootloaderObjs.o_1019_synchronousCounterOverflowValue, NULL},
        {0x1020, 0x03, ODT_ARR, &ODBootloaderObjs.o_1020_verifyConfiguration,             NULL},
        {0x1200, 0x03, ODT_REC, &ODBootloaderObjs.o_1200_SDO_Server,                      NULL},
        {0x1280, 0x04, ODT_REC, &ODBootloaderObjs.o_1280_SDOClientParameter,              NULL},
        {0x1400, 0x03, ODT_REC, &ODBootloaderObjs.o_1400_receivePDO_Communication_1,      NULL},
        {0x1401, 0x03, ODT_REC, &ODBootloaderObjs.o_1401_receivePDO_Communication_2,      NULL},
        {0x1600, 0x02, ODT_REC, &ODBootloaderObjs.o_1600_receivePDO_Mapping_1,            NULL},
        {0x1601, 0x02, ODT_REC, &ODBootloaderObjs.o_1601_receivePDO_Mapping_2,            NULL},
        {0x1800, 0x06, ODT_REC, &ODBootloaderObjs.o_1800_transmitPDO_Communication_1,     NULL},
        {0x1801, 0x06, ODT_REC, &ODBootloaderObjs.o_1801_transmitPDO_Communication_2,     NULL},
        {0x1802, 0x06, ODT_REC, &ODBootloaderObjs.o_1802_transmitPDO_Communication_3,     NULL},
        {0x1804, 0x06, ODT_REC, &ODBootloaderObjs.o_1804_transmitPDO_Communication_5,     NULL},
        {0x1805, 0x06, ODT_REC, &ODBootloaderObjs.o_1805_transmitPDO_Communication_6,     NULL},
        {0x1806, 0x06, ODT_REC, &ODBootloaderObjs.o_1806_transmitPDO_Communication_7,     NULL},
        {0x1807, 0x06, ODT_REC, &ODBootloaderObjs.o_1807_transmitPDO_Communication_8,     NULL},
        {0x1A00, 0x02, ODT_REC, &ODBootloaderObjs.o_1A00_transmitPDO_Mapping_1,           NULL},
        {0x1A01, 0x03, ODT_REC, &ODBootloaderObjs.o_1A01_transmitPDO_Mapping_2,           NULL},
        {0x1A02, 0x02, ODT_REC, &ODBootloaderObjs.o_1A02_transmitPDO_Mapping_3,           NULL},
        {0x1A04, 0x03, ODT_REC, &ODBootloaderObjs.o_1A04_transmitPDO_Mapping_5,           NULL},
        {0x1A05, 0x03, ODT_REC, &ODBootloaderObjs.o_1A05_transmitPDO_Mapping_6,           NULL},
        {0x1A06, 0x03, ODT_REC, &ODBootloaderObjs.o_1A06_transmitPDO_Mapping_7,           NULL},
        {0x1A07, 0x03, ODT_REC, &ODBootloaderObjs.o_1A07_transmitPDO_Mapping_8,           NULL},
        {0x6000, 0x01, ODT_VAR, &ODBootloaderObjs.o_6000_firmware_crc32,                  NULL},
        {0x6001, 0x01, ODT_VAR, &ODBootloaderObjs.o_6001_firmware_size,                   NULL},
        {0x6003, 0x01, ODT_VAR, &ODBootloaderObjs.o_6003_firmware_binary,                 NULL},
        {0x0000, 0x00, 0, NULL,                                                    NULL}
};

static OD_t _ODBootloader = {
        (sizeof(ODBootloaderList) / sizeof(ODBootloaderList[0])) - 1,
        &ODBootloaderList[0]
};

OD_t *ODBootloader = &_ODBootloader;
