/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   ODCrit.h; ODCrit.c
        Project File: ODCrit.eds
        File Version: 0

        Created:      29/03/2022 09:26:00
        Created By:   Unknown
        Modified:     19/02/2024 11:52:00
        Modified By:  Unknown

    Device Info:
        Vendor Name:  TU Brno Racing
        Vendor ID:    0x00000002
        Product Name: H7
        Product ID:   0x00000000

        Description:  None
*******************************************************************************/

#ifndef ODCrit_H
#define ODCrit_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define ODCrit_CNT_HB_CONS 1
#define ODCrit_CNT_HB_PROD 1
#define ODCrit_CNT_NMT 1
#define ODCrit_CNT_EM 1
#define ODCrit_CNT_EM_PROD 1
#define ODCrit_CNT_SDO_SRV 1
#define ODCrit_CNT_SDO_CLI 1
#define ODCrit_CNT_TIME 1
#define ODCrit_CNT_SYNC 1
#define ODCrit_CNT_RPDO 3
#define ODCrit_CNT_TPDO 1
#define ODCrit_CNT_GFC 0
#define ODCrit_CNT_SRDO 0


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define ODCrit_CNT_ARR_1003 4
#define ODCrit_CNT_ARR_1010 4
#define ODCrit_CNT_ARR_1011 4
#define ODCrit_CNT_ARR_1016 4
#define ODCrit_CNT_ARR_1020 2

/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1002_manufacturerStatusRegister;
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[ODCrit_CNT_ARR_1003];
    uint32_t x1005_SYNC_COB_ID;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    char x1008_manufacturerDeviceName[9];
    char x1009_manufacturerHardwareVersion[9];
    char x100A_manufacturerSoftwareVersion[9];
    uint8_t x1010_storeParameters_sub0;
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1012_timeStampCOB_ID;
    uint32_t x1013_highResolutionTimeStamp;
    uint32_t x1014_emergencyCOB_ID;
    uint16_t x1015_emergencyInhibitTime;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[ODCrit_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1020_verifyConfiguration_sub0;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDO_Server;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServer;
        uint32_t COB_IDServerToClient;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1400_receivePDO_Communication_1;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1401_receivePDO_Communication_2;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1402_receivePDO_Communication_3;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
        uint32_t mapping_3;
    } x1600_receivePDO_Mapping_1;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
        uint32_t mapping_3;
    } x1601_receivePDO_Mapping_2;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
    } x1602_receivePDO_Mapping_3;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1800_transmitPDO_Communication_1;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
    } x1A00_transmitPDO_Mapping_1;
} ODCrit_RAM_t;

#ifndef ODCrit_ATTR_RAM
#define ODCrit_ATTR_RAM
#endif
extern ODCrit_ATTR_RAM ODCrit_RAM_t ODCrit_RAM;

#ifndef ODCrit_ATTR_OD
#define ODCrit_ATTR_OD
#endif
extern ODCrit_ATTR_OD OD_t *ODCrit;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define ODCrit_ENTRY_H1000 &ODCrit->list[0]
#define ODCrit_ENTRY_H1001 &ODCrit->list[1]
#define ODCrit_ENTRY_H1002 &ODCrit->list[2]
#define ODCrit_ENTRY_H1003 &ODCrit->list[3]
#define ODCrit_ENTRY_H1005 &ODCrit->list[4]
#define ODCrit_ENTRY_H1006 &ODCrit->list[5]
#define ODCrit_ENTRY_H1007 &ODCrit->list[6]
#define ODCrit_ENTRY_H1008 &ODCrit->list[7]
#define ODCrit_ENTRY_H1009 &ODCrit->list[8]
#define ODCrit_ENTRY_H100A &ODCrit->list[9]
#define ODCrit_ENTRY_H1010 &ODCrit->list[10]
#define ODCrit_ENTRY_H1011 &ODCrit->list[11]
#define ODCrit_ENTRY_H1012 &ODCrit->list[12]
#define ODCrit_ENTRY_H1013 &ODCrit->list[13]
#define ODCrit_ENTRY_H1014 &ODCrit->list[14]
#define ODCrit_ENTRY_H1015 &ODCrit->list[15]
#define ODCrit_ENTRY_H1016 &ODCrit->list[16]
#define ODCrit_ENTRY_H1017 &ODCrit->list[17]
#define ODCrit_ENTRY_H1018 &ODCrit->list[18]
#define ODCrit_ENTRY_H1019 &ODCrit->list[19]
#define ODCrit_ENTRY_H1020 &ODCrit->list[20]
#define ODCrit_ENTRY_H1200 &ODCrit->list[21]
#define ODCrit_ENTRY_H1280 &ODCrit->list[22]
#define ODCrit_ENTRY_H1400 &ODCrit->list[23]
#define ODCrit_ENTRY_H1401 &ODCrit->list[24]
#define ODCrit_ENTRY_H1402 &ODCrit->list[25]
#define ODCrit_ENTRY_H1600 &ODCrit->list[26]
#define ODCrit_ENTRY_H1601 &ODCrit->list[27]
#define ODCrit_ENTRY_H1602 &ODCrit->list[28]
#define ODCrit_ENTRY_H1800 &ODCrit->list[29]
#define ODCrit_ENTRY_H1A00 &ODCrit->list[30]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define ODCrit_ENTRY_H1000_deviceType &ODCrit->list[0]
#define ODCrit_ENTRY_H1001_errorRegister &ODCrit->list[1]
#define ODCrit_ENTRY_H1002_manufacturerStatusRegister &ODCrit->list[2]
#define ODCrit_ENTRY_H1003_pre_definedErrorField &ODCrit->list[3]
#define ODCrit_ENTRY_H1005_SYNC_COB_ID &ODCrit->list[4]
#define ODCrit_ENTRY_H1006_communicationCyclePeriod &ODCrit->list[5]
#define ODCrit_ENTRY_H1007_synchronousWindowLength &ODCrit->list[6]
#define ODCrit_ENTRY_H1008_manufacturerDeviceName &ODCrit->list[7]
#define ODCrit_ENTRY_H1009_manufacturerHardwareVersion &ODCrit->list[8]
#define ODCrit_ENTRY_H100A_manufacturerSoftwareVersion &ODCrit->list[9]
#define ODCrit_ENTRY_H1010_storeParameters &ODCrit->list[10]
#define ODCrit_ENTRY_H1011_restoreDefaultParameters &ODCrit->list[11]
#define ODCrit_ENTRY_H1012_timeStampCOB_ID &ODCrit->list[12]
#define ODCrit_ENTRY_H1013_highResolutionTimeStamp &ODCrit->list[13]
#define ODCrit_ENTRY_H1014_emergencyCOB_ID &ODCrit->list[14]
#define ODCrit_ENTRY_H1015_emergencyInhibitTime &ODCrit->list[15]
#define ODCrit_ENTRY_H1016_consumerHeartbeatTime &ODCrit->list[16]
#define ODCrit_ENTRY_H1017_producerHeartbeatTime &ODCrit->list[17]
#define ODCrit_ENTRY_H1018_identity &ODCrit->list[18]
#define ODCrit_ENTRY_H1019_synchronousCounterOverflowValue &ODCrit->list[19]
#define ODCrit_ENTRY_H1020_verifyConfiguration &ODCrit->list[20]
#define ODCrit_ENTRY_H1200_SDO_Server &ODCrit->list[21]
#define ODCrit_ENTRY_H1280_SDOClientParameter &ODCrit->list[22]
#define ODCrit_ENTRY_H1400_receivePDO_Communication_1 &ODCrit->list[23]
#define ODCrit_ENTRY_H1401_receivePDO_Communication_2 &ODCrit->list[24]
#define ODCrit_ENTRY_H1402_receivePDO_Communication_3 &ODCrit->list[25]
#define ODCrit_ENTRY_H1600_receivePDO_Mapping_1 &ODCrit->list[26]
#define ODCrit_ENTRY_H1601_receivePDO_Mapping_2 &ODCrit->list[27]
#define ODCrit_ENTRY_H1602_receivePDO_Mapping_3 &ODCrit->list[28]
#define ODCrit_ENTRY_H1800_transmitPDO_Communication_1 &ODCrit->list[29]
#define ODCrit_ENTRY_H1A00_transmitPDO_Mapping_1 &ODCrit->list[30]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define ODCrit_INIT_CONFIG(config) {\
    (config).CNT_NMT = ODCrit_CNT_NMT;\
    (config).ENTRY_H1017 = ODCrit_ENTRY_H1017;\
    (config).CNT_HB_CONS = ODCrit_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = ODCrit_CNT_ARR_1016;\
    (config).ENTRY_H1016 = ODCrit_ENTRY_H1016;\
    (config).CNT_EM = ODCrit_CNT_EM;\
    (config).ENTRY_H1001 = ODCrit_ENTRY_H1001;\
    (config).ENTRY_H1014 = ODCrit_ENTRY_H1014;\
    (config).ENTRY_H1015 = ODCrit_ENTRY_H1015;\
    (config).CNT_ARR_1003 = ODCrit_CNT_ARR_1003;\
    (config).ENTRY_H1003 = ODCrit_ENTRY_H1003;\
    (config).CNT_SDO_SRV = ODCrit_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = ODCrit_ENTRY_H1200;\
    (config).CNT_SDO_CLI = ODCrit_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = ODCrit_ENTRY_H1280;\
    (config).CNT_TIME = ODCrit_CNT_TIME;\
    (config).ENTRY_H1012 = ODCrit_ENTRY_H1012;\
    (config).CNT_SYNC = ODCrit_CNT_SYNC;\
    (config).ENTRY_H1005 = ODCrit_ENTRY_H1005;\
    (config).ENTRY_H1006 = ODCrit_ENTRY_H1006;\
    (config).ENTRY_H1007 = ODCrit_ENTRY_H1007;\
    (config).ENTRY_H1019 = ODCrit_ENTRY_H1019;\
    (config).CNT_RPDO = ODCrit_CNT_RPDO;\
    (config).ENTRY_H1400 = ODCrit_ENTRY_H1400;\
    (config).ENTRY_H1600 = ODCrit_ENTRY_H1600;\
    (config).CNT_TPDO = ODCrit_CNT_TPDO;\
    (config).ENTRY_H1800 = ODCrit_ENTRY_H1800;\
    (config).ENTRY_H1A00 = ODCrit_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = ODCrit_CNT_GFC;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = ODCrit_CNT_SRDO;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* ODCrit_H */
