/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   ODGen.h; ODGen.c
        Project File: ODGen.eds
        File Version: 0

        Created:      29/03/2022 09:26:00
        Created By:   Unknown
        Modified:     19/02/2024 11:52:00
        Modified By:  Unknown

    Device Info:
        Vendor Name:  TU Brno Racing
        Vendor ID:    0x00000002
        Product Name: H7
        Product ID:   0x00000000

        Description:  None
*******************************************************************************/

#ifndef ODGen_H
#define ODGen_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define ODGen_CNT_HB_CONS 1
#define ODGen_CNT_HB_PROD 1
#define ODGen_CNT_NMT 1
#define ODGen_CNT_EM 1
#define ODGen_CNT_EM_PROD 1
#define ODGen_CNT_SDO_SRV 1
#define ODGen_CNT_SDO_CLI 1
#define ODGen_CNT_TIME 1
#define ODGen_CNT_SYNC 1
#define ODGen_CNT_RPDO 3
#define ODGen_CNT_TPDO 1
#define ODGen_CNT_GFC 0
#define ODGen_CNT_SRDO 0


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define ODGen_CNT_ARR_1003 4
#define ODGen_CNT_ARR_1010 4
#define ODGen_CNT_ARR_1011 4
#define ODGen_CNT_ARR_1016 4
#define ODGen_CNT_ARR_1020 2

/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1002_manufacturerStatusRegister;
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[ODGen_CNT_ARR_1003];
    uint32_t x1005_SYNC_COB_ID;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    char x1008_manufacturerDeviceName[9];
    char x1009_manufacturerHardwareVersion[9];
    char x100A_manufacturerSoftwareVersion[9];
    uint8_t x1010_storeParameters_sub0;
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1012_timeStampCOB_ID;
    uint32_t x1013_highResolutionTimeStamp;
    uint32_t x1014_emergencyCOB_ID;
    uint16_t x1015_emergencyInhibitTime;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[ODGen_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1020_verifyConfiguration_sub0;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDO_Server;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServer;
        uint32_t COB_IDServerToClient;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1400_receivePDO_Communication_1;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1401_receivePDO_Communication_2;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
    } x1402_receivePDO_Communication_3;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
        uint32_t mapping_3;
    } x1600_receivePDO_Mapping_1;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
        uint32_t mapping_2;
        uint32_t mapping_3;
    } x1601_receivePDO_Mapping_2;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
    } x1602_receivePDO_Mapping_3;
    struct {
        uint8_t highestSubindex;
        uint32_t COB_IDUsedByPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t syncStartValue;
    } x1800_transmitPDO_Communication_1;
    struct {
        uint8_t highestSubindex;
        uint32_t mapping_1;
    } x1A00_transmitPDO_Mapping_1;
} ODGen_RAM_t;

#ifndef ODGen_ATTR_RAM
#define ODGen_ATTR_RAM
#endif
extern ODGen_ATTR_RAM ODGen_RAM_t ODGen_RAM;

#ifndef ODGen_ATTR_OD
#define ODGen_ATTR_OD
#endif
extern ODGen_ATTR_OD OD_t *ODGen;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define ODGen_ENTRY_H1000 &ODGen->list[0]
#define ODGen_ENTRY_H1001 &ODGen->list[1]
#define ODGen_ENTRY_H1002 &ODGen->list[2]
#define ODGen_ENTRY_H1003 &ODGen->list[3]
#define ODGen_ENTRY_H1005 &ODGen->list[4]
#define ODGen_ENTRY_H1006 &ODGen->list[5]
#define ODGen_ENTRY_H1007 &ODGen->list[6]
#define ODGen_ENTRY_H1008 &ODGen->list[7]
#define ODGen_ENTRY_H1009 &ODGen->list[8]
#define ODGen_ENTRY_H100A &ODGen->list[9]
#define ODGen_ENTRY_H1010 &ODGen->list[10]
#define ODGen_ENTRY_H1011 &ODGen->list[11]
#define ODGen_ENTRY_H1012 &ODGen->list[12]
#define ODGen_ENTRY_H1013 &ODGen->list[13]
#define ODGen_ENTRY_H1014 &ODGen->list[14]
#define ODGen_ENTRY_H1015 &ODGen->list[15]
#define ODGen_ENTRY_H1016 &ODGen->list[16]
#define ODGen_ENTRY_H1017 &ODGen->list[17]
#define ODGen_ENTRY_H1018 &ODGen->list[18]
#define ODGen_ENTRY_H1019 &ODGen->list[19]
#define ODGen_ENTRY_H1020 &ODGen->list[20]
#define ODGen_ENTRY_H1200 &ODGen->list[21]
#define ODGen_ENTRY_H1280 &ODGen->list[22]
#define ODGen_ENTRY_H1400 &ODGen->list[23]
#define ODGen_ENTRY_H1401 &ODGen->list[24]
#define ODGen_ENTRY_H1402 &ODGen->list[25]
#define ODGen_ENTRY_H1600 &ODGen->list[26]
#define ODGen_ENTRY_H1601 &ODGen->list[27]
#define ODGen_ENTRY_H1602 &ODGen->list[28]
#define ODGen_ENTRY_H1800 &ODGen->list[29]
#define ODGen_ENTRY_H1A00 &ODGen->list[30]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define ODGen_ENTRY_H1000_deviceType &ODGen->list[0]
#define ODGen_ENTRY_H1001_errorRegister &ODGen->list[1]
#define ODGen_ENTRY_H1002_manufacturerStatusRegister &ODGen->list[2]
#define ODGen_ENTRY_H1003_pre_definedErrorField &ODGen->list[3]
#define ODGen_ENTRY_H1005_SYNC_COB_ID &ODGen->list[4]
#define ODGen_ENTRY_H1006_communicationCyclePeriod &ODGen->list[5]
#define ODGen_ENTRY_H1007_synchronousWindowLength &ODGen->list[6]
#define ODGen_ENTRY_H1008_manufacturerDeviceName &ODGen->list[7]
#define ODGen_ENTRY_H1009_manufacturerHardwareVersion &ODGen->list[8]
#define ODGen_ENTRY_H100A_manufacturerSoftwareVersion &ODGen->list[9]
#define ODGen_ENTRY_H1010_storeParameters &ODGen->list[10]
#define ODGen_ENTRY_H1011_restoreDefaultParameters &ODGen->list[11]
#define ODGen_ENTRY_H1012_timeStampCOB_ID &ODGen->list[12]
#define ODGen_ENTRY_H1013_highResolutionTimeStamp &ODGen->list[13]
#define ODGen_ENTRY_H1014_emergencyCOB_ID &ODGen->list[14]
#define ODGen_ENTRY_H1015_emergencyInhibitTime &ODGen->list[15]
#define ODGen_ENTRY_H1016_consumerHeartbeatTime &ODGen->list[16]
#define ODGen_ENTRY_H1017_producerHeartbeatTime &ODGen->list[17]
#define ODGen_ENTRY_H1018_identity &ODGen->list[18]
#define ODGen_ENTRY_H1019_synchronousCounterOverflowValue &ODGen->list[19]
#define ODGen_ENTRY_H1020_verifyConfiguration &ODGen->list[20]
#define ODGen_ENTRY_H1200_SDO_Server &ODGen->list[21]
#define ODGen_ENTRY_H1280_SDOClientParameter &ODGen->list[22]
#define ODGen_ENTRY_H1400_receivePDO_Communication_1 &ODGen->list[23]
#define ODGen_ENTRY_H1401_receivePDO_Communication_2 &ODGen->list[24]
#define ODGen_ENTRY_H1402_receivePDO_Communication_3 &ODGen->list[25]
#define ODGen_ENTRY_H1600_receivePDO_Mapping_1 &ODGen->list[26]
#define ODGen_ENTRY_H1601_receivePDO_Mapping_2 &ODGen->list[27]
#define ODGen_ENTRY_H1602_receivePDO_Mapping_3 &ODGen->list[28]
#define ODGen_ENTRY_H1800_transmitPDO_Communication_1 &ODGen->list[29]
#define ODGen_ENTRY_H1A00_transmitPDO_Mapping_1 &ODGen->list[30]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define ODGen_INIT_CONFIG(config) {\
    (config).CNT_NMT = ODGen_CNT_NMT;\
    (config).ENTRY_H1017 = ODGen_ENTRY_H1017;\
    (config).CNT_HB_CONS = ODGen_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = ODGen_CNT_ARR_1016;\
    (config).ENTRY_H1016 = ODGen_ENTRY_H1016;\
    (config).CNT_EM = ODGen_CNT_EM;\
    (config).ENTRY_H1001 = ODGen_ENTRY_H1001;\
    (config).ENTRY_H1014 = ODGen_ENTRY_H1014;\
    (config).ENTRY_H1015 = ODGen_ENTRY_H1015;\
    (config).CNT_ARR_1003 = ODGen_CNT_ARR_1003;\
    (config).ENTRY_H1003 = ODGen_ENTRY_H1003;\
    (config).CNT_SDO_SRV = ODGen_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = ODGen_ENTRY_H1200;\
    (config).CNT_SDO_CLI = ODGen_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = ODGen_ENTRY_H1280;\
    (config).CNT_TIME = ODGen_CNT_TIME;\
    (config).ENTRY_H1012 = ODGen_ENTRY_H1012;\
    (config).CNT_SYNC = ODGen_CNT_SYNC;\
    (config).ENTRY_H1005 = ODGen_ENTRY_H1005;\
    (config).ENTRY_H1006 = ODGen_ENTRY_H1006;\
    (config).ENTRY_H1007 = ODGen_ENTRY_H1007;\
    (config).ENTRY_H1019 = ODGen_ENTRY_H1019;\
    (config).CNT_RPDO = ODGen_CNT_RPDO;\
    (config).ENTRY_H1400 = ODGen_ENTRY_H1400;\
    (config).ENTRY_H1600 = ODGen_ENTRY_H1600;\
    (config).CNT_TPDO = ODGen_CNT_TPDO;\
    (config).ENTRY_H1800 = ODGen_ENTRY_H1800;\
    (config).ENTRY_H1A00 = ODGen_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = ODGen_CNT_GFC;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = ODGen_CNT_SRDO;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* ODGen_H */
