    /*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "ODGen.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
ODGen_ATTR_RAM ODGen_RAM_t ODGen_RAM = {
        .x1000_deviceType = 0x00000191,
        .x1001_errorRegister = 0x00,
        .x1002_manufacturerStatusRegister = 0x00000000,
        .x1003_pre_definedErrorField_sub0 = 0x00,
        .x1003_pre_definedErrorField = {0x00000000, 0x00000000, 0x00000000, 0x00000000},
        .x1005_SYNC_COB_ID = 0x00000080,
        .x1006_communicationCyclePeriod = 0x00000000,
        .x1007_synchronousWindowLength = 0x00000000,
        .x1008_manufacturerDeviceName = {'1', '2', '3', '4', '5', '6', '7', '8', 0},
        .x1009_manufacturerHardwareVersion = {'1', '2', '3', '4', '5', '6', '7', '8', 0},
        .x100A_manufacturerSoftwareVersion = {'1', '2', '3', '4', '5', '6', '7', '8', 0},
        .x1010_storeParameters_sub0 = 0x04,
        .x1011_restoreDefaultParameters_sub0 = 0x04,
        .x1012_timeStampCOB_ID = 0x00000100,
        .x1013_highResolutionTimeStamp = 0x00000000,
        .x1014_emergencyCOB_ID = 0x00000080,
        .x1015_emergencyInhibitTime = 0x0000,
        .x1016_consumerHeartbeatTime_sub0 = 0x04,
        .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000},
        .x1017_producerHeartbeatTime = 0x0032,
        .x1018_identity = {
                .numberOfEntries = 0x04,
                .vendorID = 0x00000000,
                .productCode = 0x00000000,
                .revisionNumber = 0x00000000,
                .serialNumber = 0x00000000
        },
        .x1020_verifyConfiguration_sub0 = 0x02,
        .x1200_SDO_Server = {
                .highestSubindex = 0x02,
                .COB_IDClientToServerRx = 0x00000600,
                .COB_IDServerToClientTx = 0x00000580
        },
        .x1280_SDOClientParameter = {
                .highestSub_indexSupported = 0x03,
                .COB_IDClientToServer = 0x80000000,
                .COB_IDServerToClient = 0x80000000,
                .node_IDOfTheSDOServer = 0x01
        },
        .x1400_receivePDO_Communication_1 = {
                .highestSubindex = 0x02,
                .COB_IDUsedByPDO = 0x40000181,
                .transmissionType = 0x00
        },
        .x1401_receivePDO_Communication_2 = {
                .highestSubindex = 0x02,
                .COB_IDUsedByPDO = 0x40000182,
                .transmissionType = 0x00
        },
        .x1402_receivePDO_Communication_3 = {
                .highestSubindex = 0x02,
                .COB_IDUsedByPDO = 0x40000391,
                .transmissionType = 0x00
        },
        .x1600_receivePDO_Mapping_1 = {
                .highestSubindex = 0x03,
                .mapping_1 = 0x60000010,
                .mapping_2 = 0x60030208,
                .mapping_3 = 0x60030308
        },
        .x1601_receivePDO_Mapping_2 = {
                .highestSubindex = 0x03,
                .mapping_1 = 0x60010010,
                .mapping_2 = 0x60030308,
                .mapping_3 = 0x60030408
        },
        .x1602_receivePDO_Mapping_3 = {
                .highestSubindex = 0x01,
                .mapping_1 = 0x60040020
        },
        .x1800_transmitPDO_Communication_1 = {
                .highestSubindex = 0x06,
                .COB_IDUsedByPDO = 0x40000289,
                .transmissionType = 0x00,
                .inhibitTime = 0x0000,
                .eventTimer = 0x000A,
                .syncStartValue = 0x00
        },
        .x1A00_transmitPDO_Mapping_1 = {
                .highestSubindex = 0x01,
                .mapping_1 = 0x60020020
        },
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_var_t o_1002_manufacturerStatusRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_SYNC_COB_ID;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_var_t o_1008_manufacturerDeviceName;
    OD_obj_var_t o_1009_manufacturerHardwareVersion;
    OD_obj_var_t o_100A_manufacturerSoftwareVersion;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_timeStampCOB_ID;
    OD_obj_var_t o_1013_highResolutionTimeStamp;
    OD_obj_var_t o_1014_emergencyCOB_ID;
    OD_obj_var_t o_1015_emergencyInhibitTime;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_array_t o_1020_verifyConfiguration;
    OD_obj_record_t o_1200_SDO_Server[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_receivePDO_Communication_1[3];
    OD_obj_record_t o_1401_receivePDO_Communication_2[3];
    OD_obj_record_t o_1402_receivePDO_Communication_3[3];
    OD_obj_record_t o_1600_receivePDO_Mapping_1[4];
    OD_obj_record_t o_1601_receivePDO_Mapping_2[4];
    OD_obj_record_t o_1602_receivePDO_Mapping_3[2];
    OD_obj_record_t o_1800_transmitPDO_Communication_1[6];
    OD_obj_record_t o_1A00_transmitPDO_Mapping_1[2];
} ODGenObjs_t;

static CO_PROGMEM ODGenObjs_t ODGenObjs = {
        .o_1000_deviceType = {
                .dataOrig = &ODGen_RAM.x1000_deviceType,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
        },
        .o_1001_errorRegister = {
                .dataOrig = &ODGen_RAM.x1001_errorRegister,
                .attribute = ODA_SDO_R | ODA_TRPDO,
                .dataLength = 1
        },
        .o_1002_manufacturerStatusRegister = {
                .dataOrig = &ODGen_RAM.x1002_manufacturerStatusRegister,
                .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                .dataLength = 4
        },
        .o_1003_pre_definedErrorField = {
                .dataOrig0 = &ODGen_RAM.x1003_pre_definedErrorField_sub0,
                .dataOrig = &ODGen_RAM.x1003_pre_definedErrorField[0],
                .attribute0 = ODA_SDO_RW,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1005_SYNC_COB_ID = {
                .dataOrig = &ODGen_RAM.x1005_SYNC_COB_ID,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
        },
        .o_1006_communicationCyclePeriod = {
                .dataOrig = &ODGen_RAM.x1006_communicationCyclePeriod,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
        },
        .o_1007_synchronousWindowLength = {
                .dataOrig = &ODGen_RAM.x1007_synchronousWindowLength,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
        },
        .o_1008_manufacturerDeviceName = {
                .dataOrig = &ODGen_RAM.x1008_manufacturerDeviceName[0],
                .attribute = ODA_SDO_R | ODA_STR,
                .dataLength = 8
        },
        .o_1009_manufacturerHardwareVersion = {
                .dataOrig = &ODGen_RAM.x1009_manufacturerHardwareVersion[0],
                .attribute = ODA_SDO_R | ODA_STR,
                .dataLength = 8
        },
        .o_100A_manufacturerSoftwareVersion = {
                .dataOrig = &ODGen_RAM.x100A_manufacturerSoftwareVersion[0],
                .attribute = ODA_SDO_R | ODA_STR,
                .dataLength = 8
        },
        .o_1010_storeParameters = {
                .dataOrig0 = &ODGen_RAM.x1010_storeParameters_sub0,
                .dataOrig = NULL,
                .attribute0 = ODA_SDO_R,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1011_restoreDefaultParameters = {
                .dataOrig0 = &ODGen_RAM.x1011_restoreDefaultParameters_sub0,
                .dataOrig = NULL,
                .attribute0 = ODA_SDO_R,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1012_timeStampCOB_ID = {
                .dataOrig = &ODGen_RAM.x1012_timeStampCOB_ID,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 4
        },
        .o_1013_highResolutionTimeStamp = {
                .dataOrig = &ODGen_RAM.x1013_highResolutionTimeStamp,
                .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
                .dataLength = 4
        },
        .o_1014_emergencyCOB_ID = {
                .dataOrig = &ODGen_RAM.x1014_emergencyCOB_ID,
                .attribute = ODA_SDO_R | ODA_MB,
                .dataLength = 4
        },
        .o_1015_emergencyInhibitTime = {
                .dataOrig = &ODGen_RAM.x1015_emergencyInhibitTime,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
        },
        .o_1016_consumerHeartbeatTime = {
                .dataOrig0 = &ODGen_RAM.x1016_consumerHeartbeatTime_sub0,
                .dataOrig = &ODGen_RAM.x1016_consumerHeartbeatTime[0],
                .attribute0 = ODA_SDO_R,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1017_producerHeartbeatTime = {
                .dataOrig = &ODGen_RAM.x1017_producerHeartbeatTime,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataLength = 2
        },
        .o_1018_identity = {
                {
                        .dataOrig = &ODGen_RAM.x1018_identity.numberOfEntries,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1018_identity.vendorID,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1018_identity.productCode,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1018_identity.revisionNumber,
                        .subIndex = 3,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1018_identity.serialNumber,
                        .subIndex = 4,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1019_synchronousCounterOverflowValue = {
                .dataOrig = NULL,
                .attribute = ODA_SDO_R,
                .dataLength = 1
        },
        .o_1020_verifyConfiguration = {
                .dataOrig0 = &ODGen_RAM.x1020_verifyConfiguration_sub0,
                .dataOrig = NULL,
                .attribute0 = ODA_SDO_R,
                .attribute = ODA_SDO_RW | ODA_MB,
                .dataElementLength = 4,
                .dataElementSizeof = sizeof(uint32_t)
        },
        .o_1200_SDO_Server = {
                {
                        .dataOrig = &ODGen_RAM.x1200_SDO_Server.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1200_SDO_Server.COB_IDClientToServerRx,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1200_SDO_Server.COB_IDServerToClientTx,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1280_SDOClientParameter = {
                {
                        .dataOrig = &ODGen_RAM.x1280_SDOClientParameter.highestSub_indexSupported,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1280_SDOClientParameter.COB_IDClientToServer,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1280_SDOClientParameter.COB_IDServerToClient,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1400_receivePDO_Communication_1 = {
                {
                        .dataOrig = &ODGen_RAM.x1400_receivePDO_Communication_1.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1400_receivePDO_Communication_1.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1400_receivePDO_Communication_1.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1401_receivePDO_Communication_2 = {
                {
                        .dataOrig = &ODGen_RAM.x1401_receivePDO_Communication_2.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1401_receivePDO_Communication_2.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1401_receivePDO_Communication_2.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1402_receivePDO_Communication_3 = {
                {
                        .dataOrig = &ODGen_RAM.x1402_receivePDO_Communication_3.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1402_receivePDO_Communication_3.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1402_receivePDO_Communication_3.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1600_receivePDO_Mapping_1 = {
                {
                        .dataOrig = &ODGen_RAM.x1600_receivePDO_Mapping_1.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1600_receivePDO_Mapping_1.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1600_receivePDO_Mapping_1.mapping_2,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1600_receivePDO_Mapping_1.mapping_3,
                        .subIndex = 3,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1601_receivePDO_Mapping_2 = {
                {
                        .dataOrig = &ODGen_RAM.x1601_receivePDO_Mapping_2.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1601_receivePDO_Mapping_2.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1601_receivePDO_Mapping_2.mapping_2,
                        .subIndex = 2,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1601_receivePDO_Mapping_2.mapping_3,
                        .subIndex = 3,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1602_receivePDO_Mapping_3 = {
                {
                        .dataOrig = &ODGen_RAM.x1602_receivePDO_Mapping_3.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1602_receivePDO_Mapping_3.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
        .o_1800_transmitPDO_Communication_1 = {
                {
                        .dataOrig = &ODGen_RAM.x1800_transmitPDO_Communication_1.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1800_transmitPDO_Communication_1.COB_IDUsedByPDO,
                        .subIndex = 1,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 4
                },
                {
                        .dataOrig = &ODGen_RAM.x1800_transmitPDO_Communication_1.transmissionType,
                        .subIndex = 2,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1800_transmitPDO_Communication_1.inhibitTime,
                        .subIndex = 3,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODGen_RAM.x1800_transmitPDO_Communication_1.eventTimer,
                        .subIndex = 5,
                        .attribute = ODA_SDO_RW | ODA_MB,
                        .dataLength = 2
                },
                {
                        .dataOrig = &ODGen_RAM.x1800_transmitPDO_Communication_1.syncStartValue,
                        .subIndex = 6,
                        .attribute = ODA_SDO_RW,
                        .dataLength = 1
                }
        },
        .o_1A00_transmitPDO_Mapping_1 = {
                {
                        .dataOrig = &ODGen_RAM.x1A00_transmitPDO_Mapping_1.highestSubindex,
                        .subIndex = 0,
                        .attribute = ODA_SDO_R,
                        .dataLength = 1
                },
                {
                        .dataOrig = &ODGen_RAM.x1A00_transmitPDO_Mapping_1.mapping_1,
                        .subIndex = 1,
                        .attribute = ODA_SDO_R | ODA_MB,
                        .dataLength = 4
                }
        },
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static ODGen_ATTR_OD OD_entry_t ODGenList[] = {
        {0x1000, 0x01, ODT_VAR, &ODGenObjs.o_1000_deviceType, NULL},
        {0x1001, 0x01, ODT_VAR, &ODGenObjs.o_1001_errorRegister, NULL},
        {0x1002, 0x01, ODT_VAR, &ODGenObjs.o_1002_manufacturerStatusRegister, NULL},
        {0x1003, 0x05, ODT_ARR, &ODGenObjs.o_1003_pre_definedErrorField, NULL},
        {0x1005, 0x01, ODT_VAR, &ODGenObjs.o_1005_SYNC_COB_ID, NULL},
        {0x1006, 0x01, ODT_VAR, &ODGenObjs.o_1006_communicationCyclePeriod, NULL},
        {0x1007, 0x01, ODT_VAR, &ODGenObjs.o_1007_synchronousWindowLength, NULL},
        {0x1008, 0x01, ODT_VAR, &ODGenObjs.o_1008_manufacturerDeviceName, NULL},
        {0x1009, 0x01, ODT_VAR, &ODGenObjs.o_1009_manufacturerHardwareVersion, NULL},
        {0x100A, 0x01, ODT_VAR, &ODGenObjs.o_100A_manufacturerSoftwareVersion, NULL},
        {0x1010, 0x05, ODT_ARR, &ODGenObjs.o_1010_storeParameters, NULL},
        {0x1011, 0x05, ODT_ARR, &ODGenObjs.o_1011_restoreDefaultParameters, NULL},
        {0x1012, 0x01, ODT_VAR, &ODGenObjs.o_1012_timeStampCOB_ID, NULL},
        {0x1013, 0x01, ODT_VAR, &ODGenObjs.o_1013_highResolutionTimeStamp, NULL},
        {0x1014, 0x01, ODT_VAR, &ODGenObjs.o_1014_emergencyCOB_ID, NULL},
        {0x1015, 0x01, ODT_VAR, &ODGenObjs.o_1015_emergencyInhibitTime, NULL},
        {0x1016, 0x05, ODT_ARR, &ODGenObjs.o_1016_consumerHeartbeatTime, NULL},
        {0x1017, 0x01, ODT_VAR, &ODGenObjs.o_1017_producerHeartbeatTime, NULL},
        {0x1018, 0x05, ODT_REC, &ODGenObjs.o_1018_identity, NULL},
        {0x1019, 0x01, ODT_VAR, &ODGenObjs.o_1019_synchronousCounterOverflowValue, NULL},
        {0x1020, 0x03, ODT_ARR, &ODGenObjs.o_1020_verifyConfiguration, NULL},
        {0x1200, 0x03, ODT_REC, &ODGenObjs.o_1200_SDO_Server, NULL},
        {0x1280, 0x04, ODT_REC, &ODGenObjs.o_1280_SDOClientParameter, NULL},
        {0x1400, 0x03, ODT_REC, &ODGenObjs.o_1400_receivePDO_Communication_1, NULL},
        {0x1401, 0x03, ODT_REC, &ODGenObjs.o_1401_receivePDO_Communication_2, NULL},
        {0x1402, 0x03, ODT_REC, &ODGenObjs.o_1402_receivePDO_Communication_3, NULL},
        {0x1600, 0x04, ODT_REC, &ODGenObjs.o_1600_receivePDO_Mapping_1, NULL},
        {0x1601, 0x04, ODT_REC, &ODGenObjs.o_1601_receivePDO_Mapping_2, NULL},
        {0x1602, 0x02, ODT_REC, &ODGenObjs.o_1602_receivePDO_Mapping_3, NULL},
        {0x1800, 0x06, ODT_REC, &ODGenObjs.o_1800_transmitPDO_Communication_1, NULL},
        {0x1A00, 0x02, ODT_REC, &ODGenObjs.o_1A00_transmitPDO_Mapping_1, NULL},
        {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _ODGen = {
        (sizeof(ODGenList) / sizeof(ODGenList[0])) - 1,
        &ODGenList[0]
};

OD_t *ODGen = &_ODGen;
